### PR TITLE
v0-20 capitalize

### PR DESCRIPTION
**Pull request by azamiya**
#2

---
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/rah-aoj-dojo/3)

### CODE REVIEW

**Comment by rhmtrz** [comment]
Removed WIP

**Comment by azamiya** [comment]
っ'-')╮ =͟͟͞͞ :shit:  ﾌﾞｫﾝ

---

Review status: 0 of 2 files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/tigerscave/rah-aoj-dojo/3#-:-LF-eD8U0ra5UO4sAA0t:b9jybb3)*

**Comment by rhmtrz** [comment]
fixed the capitalization bug

**Comment by azamiya** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/tigerscave/rah-aoj-dojo/3)*

**Pull request merged**
